# TODO Make region dynamic
steps:
# Caching is currently broken:
# https://github.com/GoogleContainerTools/kaniko/issues/521
# - name: 'gcr.io/kaniko-project/executor:latest'
  # args:
  # - --destination=europe-west1-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA
  # - --cache=true
  # - --cache-ttl=96h
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'europe-west1-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA', 
          '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
          'europe-west1-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - run
  - deploy
  - app
  - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA
  - --region=europe-west1
  - --allow-unauthenticated
  - --no-cpu-boost
  - --memory=265Mi
  - --log-http
  - --service-account=${_SERVICE_ACCOUNT}
  - --set-env-vars=CLIENT_ID=${_CLIENT_ID}
  - --set-env-vars=CLIENT_SECRET=${_CLIENT_SECRET}
  - --set-env-vars=PROJECT_ID=${_PROJECT_ID}
  - --set-env-vars=QUEUE_LOCATION=${_QUEUE_LOCATION}
  - --set-env-vars=SITE_BASE=${_SITE_BASE}
  - --set-env-vars=CLOUD_TASKS_SERVICE_ACCOUNT=${_CLOUD_TASKS_SERVICE_ACCOUNT}
options:
  # logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET