steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/google-meet-timer:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=96h
options:
  logging: REGIONAL_USER_OWNED_BUCKET
images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/google-meet-timer:$COMMIT_SHA'