steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  # Caching is currently broken:
  # https://github.com/GoogleContainerTools/kaniko/issues/521
  - --destination=europe-west3-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=96h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - run
  - deploy
  - app
  - --image=europe-west3-docker.pkg.dev/$PROJECT_ID/repo/no-meeting-overtime:$COMMIT_SHA
  - --region=europe-west3
  - --allow-unauthenticated
  - --no-cpu-boost
  - --memory=265Mi
options:
  # logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET