steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  # Caching is currently broken:
  # https://github.com/GoogleContainerTools/kaniko/issues/521
  - --destination=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/google-meet-timer:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=96h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - run
  - deploy
  - google-meet-timer
  - --image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/google-meet-timer:$COMMIT_SHA
  - --region=europe-west3
  - --allow-unauthenticated
  - --no-cpu-boost
  - --memory=265Mi
  - --tag=gcb-trigger-id=5dd5187e-2c6b-4d85-80c9-ca6c4cccb763
options:
  logging: CLOUD_LOGGING_ONLY
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET